### ISSUE TITLE
Properties to disable year & decade & century selection panels

### ISSUE THREAD

**Issue by lmorchard** [react-component/calendar#247]
The ability to select a decade and then a century has confused a few of our users, so we'd like to be able to shut it off. Even disabling the year panel would be nice, because we don't really need date & time selection further out than a few months.

**Comment by benjycui** [comment]
I will not add these properties until more people think this UX should be properties.

You can use CSS `pointer-events` to disabled panels now.

**Comment by adaam2** [comment]
@benjycui Some more information about `pointer-events` above would be useful :)

**Comment by LeoGodde** [comment]
Insert `pointer-events: none` in css class `.react-calendar__navigation__label`. This will disable the event on the View switch button

**Comment by Imgubitch** [comment]
parameters next2Label={null}  and prev2Label={null} should remove arrows for decades

**Comment by ajayJayapalan** [comment]
If u still need to be it non-interactive. It's better to add a transparent div over that.
similar to 
```css
  .i-dont-let-them-click{
      position: absolute;
      left: 100px;
      display: inline-block;
      height: 40px;
      width: 150px;
  }
```
